"""Crear bitacora_accsesos

Revision ID: 5354d2e692ca
Revises: 
Create Date: 2025-12-09 23:11:03.709469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5354d2e692ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora_accesos',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.drop_column('correo_admin')

    with op.batch_alter_table('direcciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('disponibilidad_trabajadores', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'trabajadores', ['id_trabajador'], ['id_trabajador'])

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'solicitudes_servicios', ['id_solicitud'], ['id_solicitud'])
        batch_op.create_foreign_key(None, 'trabajadores', ['id_trabajador'], ['id_trabajador'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'trabajadores', ['id_trabajador'], ['id_trabajador'])

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'solicitudes_servicios', ['id_solicitud'], ['id_solicitud'])

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'solicitudes_servicios', ['id_solicitud'], ['id_solicitud'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'trabajadores', ['id_trabajador'], ['id_trabajador'])

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('descripcion_trabajo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.alter_column('foto_trabajador',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.drop_column('contrasena')
        batch_op.drop_column('nombre')
        batch_op.drop_column('correo_trabajador')
        batch_op.drop_column('telefono_trabajador')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('apellidos',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('preferencias_contacto')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('genero')
        batch_op.drop_column('zona_preferida')
        batch_op.drop_column('bio')
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('bio', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('zona_preferida', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('genero', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('preferencias_contacto', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True))
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_nullable=True)
        batch_op.alter_column('apellidos',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False)

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_trabajador', mysql.VARCHAR(collation='utf8mb4_general_ci', length=13), nullable=False))
        batch_op.add_column(sa.Column('correo_trabajador', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
        batch_op.add_column(sa.Column('contrasena', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
        batch_op.alter_column('foto_trabajador',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
        batch_op.alter_column('descripcion_trabajo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('disponibilidad_trabajadores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('direcciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_admin', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.drop_table('bitacora_accesos')
    # ### end Alembic commands ###
